site_name: Quantum & Cryptography Docs
site_description: A collection of my learnings and projects on Quantum Computing and Cryptography.
site_author: Your Name
theme: 
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: pink
    #- media: "(prefers-color-scheme: dark)"
    #  scheme: slate
    #  primary: deep purple
    #  accent: light blue
  features:
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.share
    - math 
  #logo: assets/logo.png  # Optional: Add a custom logo
  favicon: assets/favicon.ico  # Optional: Add a favicon

# Navigation structure
nav:
  - Home: index.md
  - Quantum 101:
      - Modular Arithmetic: Math_Fundamentals/modular_arithmetic.md
      - Logic Gates: Math_Fundamentals/logic_gates.md
      - Linear Algebra: 
        - Tensor: Math_Fundamentals/linear_algebr_tensor.md
        - Matrices: Math_Fundamentals/matrices.md
        - Foundations: Math_Fundamentals/foundation.md
        - Vector Space: Math_Fundamentals/vector_space.md
        - Space Transform: Math_Fundamentals/space_transform.md
      - Hilbert Space: Math_Fundamentals/hilbert_space.md
      - Probability:
        - Probability theory: Math_Fundamentals/probability_theory.md
  - Quantum Mechanics:
      - Basics:
        - Superposition, Entanglement and Reversibility: quantum_mechanics/Sup_Entg_Rev.md
        - Qubit(s): quantum_mechanics/Qubit.md
        - Quantum gates: quantum_mechanics/Quantum_logic_gates.md
        - The Bloch sphere and rotations: quantum_mechanics/TheBlochSphereAndRotation.md
      - Theorems:
        - No-cloning: quantum_mechanics/No-cloing.md
        - No-deleting: quantum_mechanics/No-deleting.md
        - No-hiding: quantum_mechanics/No-hiding.md
        - No-teleportation: quantum_mechanics/No-teleportation.md
  - Quantum Computing:
      - Basics: 
        - Basics: quantum/basics.md
        - Algorithms: quantum/algorithms.md
      - Quantum Computation: quantum/computation.md
      - Applications: quantum/applications.md
  #- Cryptography:
  #    - Fundamentals: cryptography/fundamentals.md
  #    - Symmetric Cryptography: cryptography/symmetric.md
  #    - Asymmetric Cryptography: cryptography/asymmetric.md
  #    - Quantum Cryptography: cryptography/quantum.md
  #- Quantum Cryptography:
  #    - Fundamentals: qcryptography/fundamentals.md
  #    - QKD: 
  #      - BB84: qcryptography/BB84.md
  - Quantum ML and Optimization:
      - Optimization Algorithms:
        - Quadratic Unconstrained Binary Optimization (QUBO): 
          - QUBO Intro: QuantumOpt/QOpt/QUBO.md
          - QUBO Example: QuantumOpt/jupyter_QOpt/QUBO_1_start.ipynb
          - QUBO Knapsack: QuantumOpt/jupyter_QOpt/QUBO_example_knapsack_qiskit.ipynb
          - QUBO Max-Cut and TSP: QuantumOpt/jupyter_QOpt/QUBO_example_max_cut_and_tsp_qiskit.ipynb
        - Adiabatic Quantum Computing & Quantum Annealing (AQQA): 
          - AQQA Intro: QuantumOpt/QOpt/AQQA.md
          - AQQA Example: QuantumOpt/jupyter_QOpt/AQQA_D-WAVE.ipynb
        - Quantum Approximate Optimization Algorithm (QAOA): 
          - QAOA Intro: QuantumOpt/QOpt/QAOA.md
          - QAOA D-Wave Example: QuantumOpt/jupyter_QOpt/QAOA_D-Wave.ipynb.ipynb
          - QAOA PennyLane Example: QuantumOpt/jupyter_QOpt/QAOA_PennyLane.ipynb
        - Grover Adaptive Search (GAS): 
          - GAS Intro: QuantumOpt/QOpt/GAS.md
          - GAS Example: QuantumOpt/jupyter_QOpt/GAS_Qiskit_molecule.ipynb
        - Variational Quantum Eignesolver (VQE): 
          - VQE Intro: QuantumOpt/QOpt/VQEIntro.md
          - VQE Example: QuantumOpt/jupyter_QOpt/VQE_Qiskit_molecule.ipynb
      - Optimization Machine Learning:
        - Machine Learning Refresher: QuantumOpt/MachineLearningRefresher.md
        - Quantum Support Vector Machines (QSVM): 
          - QSVM Intro: QuantumOpt/QML/QSVM.md
          - QSVM Example: QuantumOpt/jupyter_QML/(C)load_wine_QSVM_PennyLane.ipynb
        - Quantum Neural Networks (QNN): 
          - QNN Intro: QuantumOpt/QML/QNN.md
        - Quantum Hybrid Architectures (QHybrid): 
          - QHybrid Intro: QuantumOpt/QML/QHyb.md
        - Quantum Generative Adversarial Networks (QGAN): 
          - QGANS Intro: QuantumOpt/QML/QGANS.md
  - Classical ML and Optimization:
    - Optimization Algorithms:
      - Gradient descent: ClscOptML/COpt/Gradient.md
    - Machine Learning: 
      - Support Vector Machines (SVM): ClscOptML/CML/SVM.md
  - Real-world Problems:
      - Scheduling:
        - Nurse Scheduling: Projs/Projs_Opt/Proj_Nurse_Scheduling.md
        - Nurse Scheduling Using Qiskit: Projs/jupyter_Opt/(C)nurse_scheduling_qiskit.ipynb
        - Flow Shop Scheduling: Projs/Projs_Opt/Proj_Flow_Shop_Scheduling.md
        - Air traffic control - Optimal Runway Allocation for Single-Plane Assignments in a Multi-Runway Airport: Projs/jupyter_Opt/(C)Air_Traffic_Control_1_Runway.ipynb
      - Finance:
        - Quantum Amplitude Estimation: 
          - Quantum Amplitude Estimation: Projs/Projs_Opt/Proj_quantum_amplitude_estimation.md
          - Constructing Quantum Circuit: Projs/Projs_Opt/Proj_quantum_amplitude_estimation_Q_circuit.md
          - Convergence and Accuracy: Projs/Projs_Opt/Proj_quantum_amplitude_estimation_conv_accuracy.md
          - VaR and CVaR: Projs/Projs_Opt/Proj_quantum_amplitude_estimation_Var_n_CVaR.md
        - Credit Risk Analysis: 
          - Credit Risk Analysis: Projs/Projs_Opt/Proj_credit_risk_credit_risk.md
        - Portfolio Optimization: Projs/Projs_Opt/Proj_Portfolio_Optimization.md
        - Portfolio Diversification: Projs/Projs_Opt/Proj_Portfolio_Diversification.md
      - Biology:
        - RNA Folding: Projs/Projs_Opt/Proj_RNA_Folding.md
  - About Me: about.md

# Plugins
plugins:
  - mkdocs-jupyter
  - glightbox
#  - mathjax
#  - open-in-new-tab 

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-MML-AM_CHTML
  #- https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/tex-mml-chtml.js
  #- https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdnjs.cloudflare.com/ajax/libs/mermaid/10.2.4/mermaid.min.js

markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - tables
  
  # Font Formatting: https://squidfunk.github.io/mkdocs-material/reference/formatting/
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

  # List: https://squidfunk.github.io/mkdocs-material/reference/lists/
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  # Callout: https://squidfunk.github.io/mkdocs-material/reference/admonitions/
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/pcchouCR97/mkdocs-material-tutorial
    - icon: fontawesome/brands/twitter
      link: https://x.com/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/po-chih-chou-0638941ab/
  
  mathjax_config: |
    MathJax = {
      tex: {
        macros: {
          ket: ["\\left|#1\\right\\rangle", 1]
        }
      }
    };

copyright: |
  &copy; 2024-2025 <a href="https://github.com/pcchouCR97"  target="_blank" rel="noopener">Po-Chih Chou</a>