site_name: Quantum & Cryptography Docs
site_description: A collection of my learnings and projects on Quantum Computing and Cryptography.
site_author: Your Name
theme: 
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: pink
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: light blue
  features:
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.share
    - math 
  #logo: assets/logo.png  # Optional: Add a custom logo
  favicon: assets/favicon.ico  # Optional: Add a favicon

# Navigation structure
nav:
  - Home: index.md
  - Math Fundamentals:
      - Modular Arithmetic: Math_Fundamentals/modular_arithmetic.md
      - Logic Gates: Math_Fundamentals/logic_gates.md
      - Quantum Logic Gates: Math_Fundamentals/Quantum_logic_gates.md
  - Quantum Computing:
      # - Quantum Mechanics
      # - Pauli matrices
      - Basics: 
          - Basics: quantum/basics.md
          - Algorithms: quantum/algorithms.md
      - Quantum Computation: quantum/computation.md
      - Applications: quantum/applications.md
  - Cryptography:
      - Fundamentals: cryptography/fundamentals.md
      - Symmetric Cryptography: cryptography/symmetric.md
      - Asymmetric Cryptography: cryptography/asymmetric.md
      - Quantum Cryptography: cryptography/quantum.md
  - Projects:
      - Quantum Simulations: projects/quantum-simulations.md
      - Cryptography Implementations: projects/crypto-implementations.md
  - About Me: about.md

# Plugins
#plugins:
#  - macros

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-MML-AM_CHTML

markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  
  # Font Formatting: https://squidfunk.github.io/mkdocs-material/reference/formatting/
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

  # List: https://squidfunk.github.io/mkdocs-material/reference/lists/
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  # Callout: https://squidfunk.github.io/mkdocs-material/reference/admonitions/
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/pcchouCR97/mkdocs-material-tutorial
    - icon: fontawesome/brands/twitter
      link: https://x.com/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/po-chih-chou-0638941ab/


copyright: |
  &copy; 2024 <a href="https://github.com/pcchouCR97"  target="_blank" rel="noopener">Po-Chih Chou</a>